# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    default-property-inclusion: non-null
  thymeleaf.cache: false
  main.show-banner: false